slam_toolbox:
  ros__parameters:
    odom_frame: odom
    map_frame: map
    base_frame: x500_lidar_2d_0/link  # Change to this (or whatever view_frames shows as the base link)
    scan_topic: /scan
    mode: mapping
    debug_logging: false
    throttle_scans: 2  # Process every 2nd scan to reduce load (optional, if still slow)
    map_update_interval: 5.0
    minimum_travel_distance: 0.5
    minimum_travel_heading: 0.5
    scan_queue_size: 100  # Increase from 10 to buffer more while waiting for TF
    use_scan_matching: true
    use_scan_barycenter: true
    correlation_search_space_dimension: 0.5
    correlation_search_space_resolution: 0.001
    correlation_search_space_smear_deviation: 0.1
    loop_search_space_dimension: 8.0
    loop_search_space_resolution: 0.05
    loop_search_space_smear_deviation: 0.03
    distance_variance_penalty: 0.5
    angle_variance_penalty: 1.0
    max_laser_range: 30.0
    sigma_hit: 0.2
    sigma_short: 0.1
    sigma_long: 0.1
    sigma_rec: 0.001
    sigma_grow: 0.0001
    use_sim_time: true
