slam_toolbox:
  ros__parameters:
    use_sim_time: true
    mode: mapping   # <-- ensures auto configure/activate
    map_frame: map
    odom_frame: uav/odom
    base_frame: uav/base_link
    provide_odom_frame: false
    scan_topic: uav/scan
    resolution: 0.05
    publish_period_sec: 0.05
    max_laser_range: 10.0
    transform_publish_period_sec: 0.05
    max_update_rate_hz: 20.0
    use_scan_matching_2d: true
    enable_loop_closure: true
    scan_queue_size: 10
    min_laser_range: 0.1

